### ISSUE TITLE
Problem on documentation website (2.x)

### ISSUE THREAD

**Issue by sardaukar** [cerebral/cerebral#1291]
I was happily reading the docs for 2.0 and I got an issue on my browser (Firefox) with the Codesandbox example:

![screen shot 2018-03-16 at 13 44 42](https://user-images.githubusercontent.com/153407/37523906-354e0d8c-2920-11e8-9963-2439e896fd33.png)

Did I do something wrong?

**Comment by christianalfoni** [comment]
Hi @sardaukar and sorry for late response. I believe this is a restriction in Firefox talking to `localhost`, which is where you would have the debugger running. It kinda sucks. I am not sure how we should solve this. We could have like a "tutorial tool" which would check the browser and warn you about this. Or we could drop the debugger completely from the tutorials. You have any thoughts on that?

Just to be clear. This is not a Cerebral bug, this is because Firefox restricts domains to talk to localhost. You can just fine use Cerebral with the debugging experience locally :)

**Comment by sardaukar** [comment]
Ok, thanks for getting back to me!

**Comment by Guria** [comment]
Problem is still here :(

@christianalfoni how about wrapping connection code with try/catch and outputtinv friendly message to console here?

**Comment by christianalfoni** [comment]
Yeah, maybe we should just fix this in Cerebral itself and note in documentation it requires Chrome due to domain limitations.

**Comment by christianalfoni** [comment]
I think we can rather solve this in the tutorials... doing try catch there, cause then we can show a warning in the UI of the tutorial so people do not overlook it. I will try something

**Comment by christianalfoni** [comment]
Okay, I updated all tutorials with a Chrome check and updated description on downloading debugger. I think this is good enough :)
